### ISSUE TITLE
<osmanip.h> not found when compiling all targets.

### ISSUE THREAD

**Issue by myermo** [JustWhit3/SAFD-algorithm#8]
Hi,

After installing the osmanip library, the file `osmanip.hpp` is copied in /usr/local/include directory. Nevertheless, the compilation of this program requires `osmanip.h`, which is a file with different extension.

`test/test_utils.cpp:10:10: fatal error: osmanip.h: File or directory doesnt exist.
   10 | #include <osmanip.h>`

The command `find /usr/local/include -iname "*osmanip*"` returns this:
`/usr/local/include/osmanip.hpp`

**Comment by JustWhit3** [comment]
Hi @myermo thanks for the issue. 

Are you sure you are using the right version of the software? Because in the current version [1.0.2](https://github.com/JustWhit3/SAFD-algorithm/releases/tag/v1.0.2)  (see [here](https://github.com/JustWhit3/SAFD-algorithm/blob/main/test/test_utils.cpp#:~:text=%23include%20%3Cosmanip.hpp%3E)) is used `osmanip.hpp`.

You can check at line 10 of the file `test/test_utils.cpp` and see which osmanip extension is used in your version of the software.

**Comment by myermo** [comment]
Yep, you are right. I cloned the repository yesterday, so this is a bit strange.

In any case, I'm still getting an error when trying to compile the tests:

```
test/test_utils.cpp:29:94: error: no match for ‘operator+’ (operand types are ‘doctest::detail::MessageBuilder’ and ‘const char [22]’)
   29 |   CHECK_THROWS_MESSAGE( throw runtime_thrower( "This is a test string" ), feat( col, "red" ) + "This is a test string" + reset( "color" ) );
```
I am using g++ 11.1.0, and I compiled doctest from scratch with ```cmake . && sudo make install```.

Do you have an idea of what's happening?

**Comment by JustWhit3** [comment]
Hi @myermo, thanks again also for this one. 

It should have been fixed with commit [5dc0067](https://github.com/JustWhit3/SAFD-algorithm/commit/5dc00676c4bd144e61ec5d656c013c63900375aa). Can you please confirm me this?

**Comment by JustWhit3** [comment]
@all-contributors please add @myermo for bug

**Comment by myermo** [comment]
> Hi @myermo, thanks again also for this one.
> 
> It should have been fixed with commit [5dc0067](https://github.com/JustWhit3/SAFD-algorithm/commit/5dc00676c4bd144e61ec5d656c013c63900375aa). Can you please confirm me this?

Hi. No, it's not fixed. You just changed a `const char*` with a... `const char*`.

I have in my system de last doctest version installed.

**Comment by JustWhit3** [comment]
You are right, the fact is that sometimes, in Doctest, if you try to sum strings, `doctest::detail::MessageBuilder` doesn't support sum between them, therefore using `const char*` should be better. However, I tried again solving the issue with commit [b93733c](https://github.com/JustWhit3/SAFD-algorithm/commit/b93733c06ed140b16de5f92a97a2a405901a683d), I wrote explicitly the full string, without summing anything. Tell me if it compiles now.

**Comment by myermo** [comment]
Yeah, is working now! Thanks for your time. I'm planning to do some PRs this week, let's see if we could improve the algorithm.

**Comment by JustWhit3** [comment]
Thank you very much! They would be really appreciated! Don't forget to read [this](https://github.com/JustWhit3/SAFD-algorithm/blob/main/doc/CONTRIBUTING.md) document before sending one of them. 

Thank you again for your time to contribute.
